;;; themian-theme.el --- My color theme

;;; Commentary:

;;; Code:

(deftheme themian
  "My color theme")


(defmacro themian-with-color-variables (&rest body)
  "Bind all variables in `themian-colors-alist'.

Taken from zenburn-theme.el"
  (declare (indent 0))
  `(let ((class '((class color) (min-colors 89)))
         ,@(mapcar (lambda (color)
                     (list (nth 0 color) (nth 1 color)))
                   themian-colors-list))
     ,@body))


(setq themian-colors-list
      '((unknown  "#9933ff")
        (grey-1   "#181818")
        (grey-2   "#222222")
        (grey-3   "#333333")
        (grey-4   "#444444")
        (white-1  "#ffffff")
        (white-2  "#eeeeee")
        (white-3  "#bbbbbb")
        (white-4  "#999999")
        (green-1  "#8CDC8C")
        (green-2  "#39A939")
        (red-1    "#993333")
        (yellow-1 "#99C542")
        (yellow-2 "#5D860C")
        ;; (blue-1   "#5275A0")
        ;; (blue-2   "#7C9ABF")
        (blue-1   "#459393")
        (blue-2   "#76B8B8")
        ))


(themian-with-color-variables
  (setq themian-faces-list
        `(
          ;; basic
          (button (:foreground ,white-1 :background ,grey-3 :box (:line-width 1 :style released-button)))
          (cursor (:background ,yellow-1))
          (default (:foreground ,white-2 :background ,grey-1 :weight normal))
          (escape-glyph (:background ,unknown))
          (font-lock-builtin-face (:foreground ,blue-2))
          (font-lock-comment-delimiter-face (:inherit font-lock-comment-face))
          (font-lock-comment-face (:foreground ,blue-1 :slant italic))
          (font-lock-constant-face (:foreground ,green-1))
          (font-lock-doc-face (:foreground ,green-2))
          (font-lock-function-name-face (:foreground ,blue-1))
          (font-lock-keyword-face (:foreground ,yellow-1))
          (font-lock-negation-char-face (:background ,unknown))
          (font-lock-preprocessor-face (:foreground ,yellow-1))
          (font-lock-regexp-grouping-backslash (:background ,unknown))
          (font-lock-regexp-grouping-construct (:background ,unknown))
          (font-lock-string-face (:foreground ,white-3))
          (font-lock-type-face (:foreground ,green-1))
          (font-lock-variable-name-face (:foreground ,white-1))
          (font-lock-warning-face (:foreground ,white-1 :background ,red-1))
          (fringe (:foreground ,white-2 :background ,grey-2))
          (header-line (:background ,grey-2))
          (highlight (:background ,grey-2))
          (link (:foreground ,yellow-1 :underline t))
          (link-visited (:background ,unknown))
          (minibuffer-prompt (:weight bold))
          (region (:background ,grey-3))
          (secondary-selection (:background ,grey-4))
          (shadow (:foreground ,blue-1))
          (tooltip (:background ,unknown))
          (trailing-whitespace (:background ,yellow-1))

          ;; rest
          (helm-M-x-key (:foreground ,white-1 :background ,grey-3 :box (:line-width 1 :style released-button)))
          (helm-action (:background ,unknown))
          (helm-bookmark-addressbook (:background ,unknown))
          (helm-bookmark-directory (:inherit helm-ff-directory))
          (helm-bookmark-file (:inherit helm-ff-file))
          (helm-bookmark-gnus (:background ,unknown))
          (helm-bookmark-info (:background ,unknown))
          (helm-bookmark-man (:background ,unknown))
          (helm-bookmark-w3m (:background ,unknown))
          (helm-buffer-directory (:inherit helm-ff-directory))
          (helm-buffer-file (:inherit helm-ff-file))
          (helm-buffer-not-saved (:weight bold))
          (helm-buffer-process (:foreground ,blue-2))
          (helm-buffer-saved-out (:background ,unknown))
          (helm-buffer-size (:foreground ,white-3))
          (helm-candidate-number (:background ,unknown))
          (helm-etags-file (:background ,unknown))
          (helm-ff-directory (:foreground ,blue-1 :weight normal))
          (helm-ff-dirs (:background ,unknown))
          (helm-ff-dotted-directory (:inherit helm-ff-directory))
          (helm-ff-dotted-symlink-directory (:inherit helm-ff-directory))
          (helm-ff-executable (:foreground ,green-1))
          (helm-ff-file (:foreground ,white-1))
          (helm-ff-invalid-symlink (:inherit font-lock-warning-face))
          (helm-ff-prefix (:foreground ,white-1 :weight bold))
          (helm-ff-symlink (:foreground ,green-2 :weight bold))
          (helm-grep-cmd-line (:background ,unknown))
          (helm-grep-file (:background ,unknown))
          (helm-grep-finish (:background ,unknown))
          (helm-grep-lineno (:background ,unknown))
          (helm-grep-match (:background ,unknown))
          (helm-header (:background ,unknown))
          (helm-header-line-left-margin (:foreground ,yellow-1 :weight bold))
          (helm-helper (:background ,unknown))
          (helm-history-deleted (:background ,unknown))
          (helm-history-remote (:background ,unknown))
          (helm-lisp-completion-info (:background ,unknown))
          (helm-lisp-show-completion (:background ,unknown))
          (helm-locate-finish (:background ,unknown))
          (helm-match (:foreground ,white-1 :background ,grey-3 :weight bold))
          (helm-match-item (:background ,unknown))
          (helm-moccur-buffer (:background ,unknown))
          (helm-prefarg (:background ,unknown))
          (helm-resume-need-update (:background ,unknown))
          (helm-selection (:inherit highlight))
          (helm-selection-line (:inherit highlight))
          (helm-separator (:background ,unknown))
          (helm-source-header (:foreground ,blue-2 :weight bold :height 1.15))
          (helm-visible-mark (:background ,unknown))
          (mode-line (:background ,grey-3 :box (:line-width -1 :color nil :style released-button)))
          (mode-line-buffer-id (:foreground ,white-1 :weight bold))
          (mode-line-emphasis (:background ,unknown))
          (mode-line-highlight (:foreground ,grey-1 :background ,yellow-1))
          (mode-line-inactive (:background ,grey-1 :foreground ,white-3 :inherit (mode-line)))
          (paren-face-match (:background ,red-1))
          (paren-face-mismatch (:background ,yellow-1))
          (paren-face-no-match (:background ,blue-1))
          (rainbow-delimiters-depth-1-face (:foreground ,white-1))
          (rainbow-delimiters-depth-10-face (:foreground ,white-2))
          (rainbow-delimiters-depth-11-face (:foreground ,white-1))
          (rainbow-delimiters-depth-12-face (:foreground ,white-2))
          (rainbow-delimiters-depth-2-face (:foreground ,white-2))
          (rainbow-delimiters-depth-3-face (:foreground ,white-1))
          (rainbow-delimiters-depth-4-face (:foreground ,white-2))
          (rainbow-delimiters-depth-5-face (:foreground ,white-1))
          (rainbow-delimiters-depth-6-face (:foreground ,white-2))
          (rainbow-delimiters-depth-7-face (:foreground ,white-1))
          (rainbow-delimiters-depth-8-face (:foreground ,white-2))
          (rainbow-delimiters-depth-9-face (:foreground ,white-1))
          (show-paren-match (:inverse-video t :weight normal))
          (show-paren-mismatch (:foreground ,red-1 :background ,grey-3))
          (spacemacs-emacs-face (:background ,blue-2))
          (spacemacs-evilified-face (:background ,unknown))
          (spacemacs-helm-navigation-ms-face (:background ,unknown))
          (spacemacs-hybrid-face (:background ,unknown))
          (spacemacs-ido-navigation-ms-face (:background ,unknown))
          (spacemacs-iedit-face (:background ,unknown))
          (spacemacs-iedit-insert-face (:background ,unknown))
          (spacemacs-insert-face (:foreground ,grey-1 :background ,green-2 :weight bold))
          (spacemacs-lisp-face (:background ,unknown))
          (spacemacs-micro-state-binding-face (:background ,unknown))
          (spacemacs-micro-state-header-face (:background ,unknown))
          (spacemacs-mode-line-new-version-lighter-error-face (:background ,unknown))
          (spacemacs-mode-line-new-version-lighter-success-face (:background ,unknown))
          (spacemacs-mode-line-new-version-lighter-warning-face (:background ,unknown))
          (spacemacs-motion-face (:foreground ,grey-1 :background ,blue-1 :weight bold))
          (spacemacs-normal-face (:foreground ,grey-1 :background ,yellow-1 :weight bold))
          (spacemacs-replace-face (:foreground ,white-2 :background ,red-1 :weight bold))
          (spacemacs-visual-face (:foreground ,grey-1 :background ,blue-1 :weight bold))

          )))


(let ((faces (mapcar (lambda (config)
                       `(,(nth 0 config) ((t ,(nth 1 config)))))
                     themian-faces-list)))
  (apply #'custom-theme-set-faces
         'themian
         faces))


;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'themian)

;;; themian-theme.el ends here
