;;; themian-theme.el --- My color theme

;;; Commentary:

;;; Code:

(deftheme themian
  "My color theme")


(defmacro themian-with-color-variables (&rest body)
  "Bind all variables in `themian-colors-alist'.

Taken from zenburn-theme.el"
  (declare (indent 0))
  `(let ((class '((class color) (min-colors 89)))
         ,@(mapcar (lambda (color)
                     (list (nth 0 color) (nth 1 color)))
                   themian-colors-list))
     ,@body))


(setq themian-colors-list
      '((unknown  "#9933ff")
        (diff-1   "#204040")
        (diff-2   "#306060")
        (diff-3   "#102020")
        (diff-4   "#183030")
        (grey-1   "#181818")
        (grey-2   "#202020")
        (grey-3   "#303030")
        (grey-4   "#404040")
        (grey-5   "#505050")
        (grey-6   "#606060")
        (white-1  "#ffffff")
        (white-2  "#eeeeee")
        (white-3  "#bbbbbb")
        (white-4  "#999999")
        (green-1  "#8CDC8C")
        (green-2  "#39A939")
        (red-1    "#993333")
        (yellow-1 "#99C542")
        (yellow-2 "#5D860C")
        (yellow-3 "#FCF0A5")
        (blue-1   "#6490C5")
        (blue-2   "#8DB2DE")
        (blue-3   "#BFD6F2")
        (blue-4   "#408080")
        (cyan-1   "#77D5D5")
        ))


(themian-with-color-variables
  (setq themian-faces-list
        `(
          ;; basic
          (button (:foreground ,white-1 :background ,grey-3 :box (:line-width 1 :style released-button)))
          (cursor (:background ,yellow-1))
          (default (:foreground ,white-2 :background ,grey-1 :weight normal))
          (escape-glyph (:foreground ,white-2 :background ,grey-4 :weight bold))
          (font-lock-builtin-face (:foreground ,blue-3))
          (font-lock-comment-delimiter-face (:inherit font-lock-comment-face))
          (font-lock-comment-face (:foreground ,cyan-1 :slant italic))
          (font-lock-constant-face (:foreground ,green-1))
          (font-lock-doc-face (:foreground ,green-2))
          (font-lock-function-name-face (:foreground ,blue-1))
          (font-lock-keyword-face (:foreground ,yellow-1))
          (font-lock-negation-char-face (:inherit default))
          (font-lock-preprocessor-face (:foreground ,yellow-3))
          (font-lock-regexp-grouping-backslash (:background ,unknown))
          (font-lock-regexp-grouping-construct (:background ,unknown))
          (font-lock-string-face (:foreground ,white-3))
          (font-lock-type-face (:foreground ,green-1))
          (font-lock-variable-name-face (:foreground ,white-1))
          (font-lock-warning-face (:foreground ,white-1 :background ,red-1))
          (fringe (:foreground ,white-2 :background ,grey-2))
          (header-line (:background ,grey-2))
          (highlight (:background ,grey-2))
          (link (:foreground ,yellow-1 :underline t))
          (link-visited (:background ,unknown))
          (minibuffer-prompt (:weight bold))
          (region (:background ,grey-3))
          (secondary-selection (:background ,grey-4))
          (shadow (:foreground ,blue-1))
          (tooltip (:background ,unknown))
          (trailing-whitespace (:background ,yellow-1))

          ;; rest
          (diff-refine-added (:box (:line-width 1 :color ,blue-2)))
          (diff-refine-changed (:background ,unknown))
          (diff-refine-removed (:inherit diff-refine-added))
          (diff-header (:background ,unknown))
          (helm-M-x-key (:foreground ,white-1 :background ,grey-3 :box (:line-width 1 :style released-button)))
          (helm-action (:background ,unknown))
          (helm-bookmark-addressbook (:background ,unknown))
          (helm-bookmark-directory (:inherit helm-ff-directory))
          (helm-bookmark-file (:inherit helm-ff-file))
          (helm-bookmark-gnus (:background ,unknown))
          (helm-bookmark-info (:background ,unknown))
          (helm-bookmark-man (:background ,unknown))
          (helm-bookmark-w3m (:background ,unknown))
          (helm-buffer-directory (:inherit helm-ff-directory))
          (helm-buffer-file (:inherit helm-ff-file))
          (helm-buffer-not-saved (:weight bold))
          (helm-buffer-process (:foreground ,blue-3))
          (helm-buffer-saved-out (:background ,unknown))
          (helm-buffer-size (:foreground ,white-3))
          (helm-candidate-number (:background ,unknown))
          (helm-etags-file (:background ,unknown))
          (helm-ff-directory (:foreground ,blue-1 :weight bold))
          (helm-ff-dirs (:background ,unknown))
          (helm-ff-dotted-directory (:inherit helm-ff-directory))
          (helm-ff-dotted-symlink-directory (:inherit helm-ff-directory))
          (helm-ff-executable (:foreground ,green-1 :weight bold))
          (helm-ff-file (:foreground ,white-1))
          (helm-ff-invalid-symlink (:inherit font-lock-warning-face))
          (helm-ff-prefix (:foreground ,white-1 :weight bold))
          (helm-ff-symlink (:foreground ,green-2 :weight bold))
          (helm-grep-cmd-line (:background ,unknown))
          (helm-grep-file (:background ,unknown))
          (helm-grep-finish (:background ,unknown))
          (helm-grep-lineno (:background ,unknown))
          (helm-grep-match (:background ,unknown))
          (helm-header (:background ,unknown))
          (helm-header-line-left-margin (:foreground ,yellow-1 :weight bold))
          (helm-helper (:background ,unknown))
          (helm-history-deleted (:background ,unknown))
          (helm-history-remote (:background ,unknown))
          (helm-lisp-completion-info (:background ,unknown))
          (helm-lisp-show-completion (:background ,unknown))
          (helm-locate-finish (:background ,unknown))
          (helm-match (:foreground ,white-1 :background ,grey-3 :weight bold))
          (helm-match-item (:background ,unknown))
          (helm-moccur-buffer (:background ,unknown))
          (helm-prefarg (:background ,unknown))
          (helm-resume-need-update (:background ,unknown))
          (helm-selection (:inherit highlight))
          (helm-selection-line (:inherit highlight))
          (helm-separator (:background ,unknown))
          (helm-source-header (:foreground ,blue-3 :weight bold :height 1.15))
          (helm-visible-mark (:background ,unknown))
          (linum (:foreground ,grey-6))
          (magit-bisect-bad (:background ,unknown))
          (magit-bisect-good (:background ,unknown))
          (magit-bisect-skip (:background ,unknown))
          (magit-blame-date (:foreground ,blue-2 :background ,grey-3))
          (magit-blame-hash (:background ,unknown))
          (magit-blame-heading (:background ,grey-3))
          (magit-blame-name (:foreground ,white-2 :background ,grey-3 :weight normal))
          (magit-blame-summary (:foreground ,white-1 :background ,grey-3 :slant italic))
          (magit-branch-current (:foreground ,blue-2 :weight bold :box (:line-width 1)))
          (magit-branch-local (:foreground ,green-2 :weight bold))
          (magit-branch-remote (:foreground ,cyan-1 :weight bold))
          (magit-cherry-equivalent (:background ,unknown))
          (magit-cherry-unmatched (:background ,unknown))
          (magit-diff-added (:background ,diff-1))
          (magit-diff-added-highlight (:foreground ,white-1 :background ,diff-2))
          (magit-diff-base (:background ,unknown))
          (magit-diff-base-highlight (:background ,unknown))
          (magit-diff-conflict-heading (:background ,unknown))
          (magit-diff-context (:background ,grey-1))
          (magit-diff-context-highlight (:background ,grey-1))
          (magit-diff-file-heading (:foreground ,blue-2))
          (magit-diff-file-heading-highlight (:inherit highlight))
          (magit-diff-file-heading-selection (:background ,unknown))
          (magit-diff-hunk-heading (:foreground ,white-3 :background ,grey-3 :slant italic))
          (magit-diff-hunk-heading-highlight (:foreground ,white-1 :background ,grey-4 :slant normal))
          (magit-diff-hunk-heading-selection (:background ,unknown))
          (magit-diff-lines-boundary (:background ,white-4))
          (magit-diff-lines-heading (:foreground ,grey-1 :background ,blue-1))
          (magit-diff-our (:background ,unknown))
          (magit-diff-our-highlight (:background ,unknown))
          (magit-diff-removed (:background ,diff-3))
          (magit-diff-removed-highlight (:foreground ,white-1 :background ,diff-4))
          (magit-diff-their (:background ,unknown))
          (magit-diff-their-highlight (:background ,unknown))
          (magit-diff-whitespace-warning (:background ,unknown))
          (magit-diffstat-added (:foreground ,green-2))
          (magit-diffstat-removed (:foreground ,red-1))
          (magit-dimmed (:background ,unknown))
          (magit-filename (:inherit default))
          (magit-hash (:foreground ,white-4))
          (magit-head (:background ,unknown))
          (magit-header-line (:foreground ,yellow-3 :weight bold))
          (magit-log-author (:foreground ,blue-3 :weight bold))
          (magit-log-date (:foreground ,green-1))
          (magit-log-graph (:inherit default))
          (magit-popup-argument (:foreground ,white-1 :weight bold))
          (magit-popup-disabled-argument (:foreground ,white-1))
          (magit-popup-heading (:foreground ,yellow-3 :weight bold))
          (magit-popup-key (:foreground ,blue-2))
          (magit-popup-option-value (:weight bold))
          (magit-process-ng (:background ,unknown))
          (magit-process-ok (:background ,unknown))
          (magit-reflog-amend (:background ,unknown))
          (magit-reflog-checkout (:background ,unknown))
          (magit-reflog-cherry-pick (:background ,unknown))
          (magit-reflog-commit (:background ,unknown))
          (magit-reflog-merge (:background ,unknown))
          (magit-reflog-other (:background ,unknown))
          (magit-reflog-rebase (:background ,unknown))
          (magit-reflog-remote (:background ,unknown))
          (magit-reflog-reset (:background ,unknown))
          (magit-refname (:background ,unknown))
          (magit-refname-stash (:background ,unknown))
          (magit-refname-wip (:background ,unknown))
          (magit-section-heading (:foreground ,yellow-3 :weight bold))
          (magit-section-heading-selection (:background ,unknown))
          (magit-section-highlight (:inherit highlight))
          (magit-section-secondary-heading (:foreground ,yellow-3))
          (magit-sequence-done (:background ,unknown))
          (magit-sequence-drop (:background ,unknown))
          (magit-sequence-head (:background ,unknown))
          (magit-sequence-onto (:background ,unknown))
          (magit-sequence-part (:background ,unknown))
          (magit-sequence-pick (:background ,unknown))
          (magit-sequence-stop (:background ,unknown))
          (magit-signature-bad (:background ,unknown))
          (magit-signature-good (:background ,unknown))
          (magit-signature-untrusted (:background ,unknown))
          (magit-tag (:foreground ,yellow-3 :weight bold :box t))
          (mode-line (:background ,grey-3 :box (:line-width -1 :color nil :style released-button)))
          (mode-line-buffer-id (:foreground ,white-1 :weight bold))
          (mode-line-emphasis (:background ,unknown))
          (mode-line-highlight (:foreground ,grey-1 :background ,yellow-1))
          (mode-line-inactive (:background ,grey-1 :foreground ,white-3 :inherit (mode-line)))
          (paren-face-match (:background ,red-1))
          (paren-face-mismatch (:background ,yellow-1))
          (paren-face-no-match (:background ,blue-1))
          (rainbow-delimiters-depth-1-face (:foreground ,white-1))
          (rainbow-delimiters-depth-10-face (:foreground ,white-2))
          (rainbow-delimiters-depth-11-face (:foreground ,white-1))
          (rainbow-delimiters-depth-12-face (:foreground ,white-2))
          (rainbow-delimiters-depth-2-face (:foreground ,white-2))
          (rainbow-delimiters-depth-3-face (:foreground ,white-1))
          (rainbow-delimiters-depth-4-face (:foreground ,white-2))
          (rainbow-delimiters-depth-5-face (:foreground ,white-1))
          (rainbow-delimiters-depth-6-face (:foreground ,white-2))
          (rainbow-delimiters-depth-7-face (:foreground ,white-1))
          (rainbow-delimiters-depth-8-face (:foreground ,white-2))
          (rainbow-delimiters-depth-9-face (:foreground ,white-1))
          (show-paren-match (:inverse-video t :weight normal))
          (show-paren-mismatch (:foreground ,red-1 :background ,grey-3))
          (spacemacs-emacs-face (:background ,blue-3))
          (spacemacs-evilified-face (:background ,blue-1))
          (spacemacs-helm-navigation-ms-face (:background ,unknown))
          (spacemacs-hybrid-face (:background ,unknown))
          (spacemacs-ido-navigation-ms-face (:background ,unknown))
          (spacemacs-iedit-face (:background ,unknown))
          (spacemacs-iedit-insert-face (:background ,unknown))
          (spacemacs-insert-face (:foreground ,grey-1 :background ,green-2 :weight bold))
          (spacemacs-lisp-face (:background ,unknown))
          (spacemacs-micro-state-binding-face (:foreground ,cyan-1)) ; XXX this is being overwritten somewhere :/
          (spacemacs-micro-state-header-face (:background ,unknown))
          (spacemacs-mode-line-new-version-lighter-error-face (:background ,unknown))
          (spacemacs-mode-line-new-version-lighter-success-face (:background ,unknown))
          (spacemacs-mode-line-new-version-lighter-warning-face (:background ,unknown))
          (spacemacs-motion-face (:foreground ,grey-1 :background ,blue-1 :weight bold))
          (spacemacs-normal-face (:foreground ,grey-1 :background ,yellow-1 :weight bold))
          (spacemacs-replace-face (:foreground ,white-2 :background ,red-1 :weight bold))
          (spacemacs-visual-face (:foreground ,grey-1 :background ,blue-1 :weight bold))

          )))


(let ((faces (mapcar (lambda (config)
                       `(,(nth 0 config) ((t ,(nth 1 config)))))
                     themian-faces-list)))
  (apply #'custom-theme-set-faces
         'themian
         faces))


;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'themian)

;;; themian-theme.el ends here
